Repository talkpick/talkpick-backend, pull requests merged in 2025-05, with the labels that each got.

#34 📦 Chore: open ai 설정 추가
  src/main/resources/application.yml
Labels: D-day

#31 ✨ Feature/#4 spring security를 활용한 로그인 기능
  build.gradle
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/in/AuthServiceUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/out/AuthTokenStorePort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/out/SecurityPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/out/UserRepositoryPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/service/AuthService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/domain/model/AuthUser.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/domain/model/TokenPair.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/domain/model/vo/TokenInfo.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/exception/AuthException.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/exception/error/AuthErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/persistence/adapter/out/jpa/UserJpaRepositoryAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/persistence/adapter/out/redis/AuthTokenStoreAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtAuthentication.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtProvider.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtVerifier.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/adapter/out/SecurityAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/custom/handler/CustomAccessDeniedHandler.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/custom/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/custom/user/CustomUserDetails.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/custom/user/CustomUserDetailsService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/filter/JwtFilter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/support/mapper/AuthUserMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/support/mapper/CustomUserDetailsMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/support/mapper/TokenMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/support/mapper/TokenVoMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/controller/AuthController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/LogoutReqDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/RefreshReqDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/SignInDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/SignUpDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/res/TokenResDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/mapper/TokenDtoMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/AbstractAuthValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/LogoutReqValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/RefreshReqValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/SignInDtoValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/SignUpDtoValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/enums/AuthValidationError.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/annotation/security/LoginUser.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/redis/RedisConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/security/JwtConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/security/SecurityConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/util/security/LoginUserUtil.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/util/security/TokenExtractUtil.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/validation/GlobalValidationAdvice.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/exception/UserException.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/exception/error/UserErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/UserRepository.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/entity/Gender.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/entity/Role.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/entity/UserEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/support/mapper/UserEntityMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/UserController.java
  src/main/resources/application.yml
Labels: D-day

#74 📦 Chore: 이슈 템플릿 및 PR 템플릿 삭제 (조직 템플릿 사용)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/epic.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/tech-debt.yml
  .github/ISSUE_TEMPLATE/user-story.yml
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/pull_request_template.md
Labels: End

#76 📦 Chore/PR 추가시 수정 사항 요약 Action 추가
  .github/workflows/gpt-code-review-supporter.yml
Labels: D-day

#81 ✨ Feature/#71 페이지 응답 데이터 클래스 추가
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/response/SliceResponse.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/adapter/dto/SliceResult.java
Labels: D-day

#63 ✨ Feature/#46 회원 부가 기능 개발
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/in/AuthServiceUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/port/out/UserRepositoryPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/application/service/AuthService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/persistence/adapter/out/jpa/UserJpaRepositoryAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/persistence/adapter/out/redis/AuthTokenStoreAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtAuthentication.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtProvider.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtVerifier.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/adapter/out/SecurityAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/custom/user/CustomUserDetailsService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/filter/JwtFilter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/support/mapper/CustomUserDetailsMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/controller/AuthController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/CheckAccountDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/CheckEmailDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/dto/req/CheckNicknameDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/AbstractAuthValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/CheckAccountValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/CheckEmailValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/CheckNicknameValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/SignUpDtoValidator.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/presentation/support/validator/enums/AuthValidationError.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/application/port/in/UserServiceUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/application/port/out/UserManagementPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/application/service/UserService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/domain/model/User.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/exception/UserException.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/exception/error/UserErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/UserManagementJpaAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/entity/Gender.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/entity/UserEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/adapter/persistence/jpa/repository/UserRepository.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/infrastructure/support/mapper/UserMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/UserController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/dto/req/UserUpdateReqDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/dto/res/UserInfoResDto.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/support/mapper/UserInfoDtoMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/user/presentation/controller/support/validator/UserUpdateReqDtoValidator.java
  src/main/resources/application.yml
Labels: D-1

#85 ✨ Feature/#84 컨트롤러 엔드포인트 통합
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/filter/JwtFilter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/security/SecurityConfig.java
Labels: D-day

#87 Feature/#70 jpa 최신 뉴스 포트 어댑터 추가
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/response/SliceResponse.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/in/NewsInfoProviderUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/out/NewsDetailProviderPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/out/NewsInfoProviderPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsInfoDetailProviderService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsInfoProviderService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/domain/model/NewsInfo.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/adapter/NewsInfoDetailProviderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/adapter/NewsInfoProviderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/converter/FloatArrayToJsonConverter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/converter/exception/JpaConvertorException.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/converter/exception/error/JpaConvertorErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/entity/ArticleEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/mapper/ArticleEntityMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/repository/NewsInfoJpaRepository.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/support/PageableBuilder.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/support/SliceResultBuilder.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/support/SortBuilder.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/NewsInfoProviderController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/dto/NewsInfoResponse.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/mapper/NewsInfoResponseMapper.java
Labels: D-day

#89 Feature/#57 채팅방 기능 개발
  build.gradle
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/in/ChatUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/in/mapper/ChatMessageRequestMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/service/ChatService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/config/RabbitMQConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/config/WebSocketConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/domain/model/ChatMessage.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/domain/model/MessageType.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/exception/ChatException.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/exception/error/ChatErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/ChatController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/dto/request/ChatMessageRequest.java
  src/main/resources/application.yml
Labels: 기능 개발

#90 Feature/#67 뉴스 조회수 저장 기능 구현
  build.gradle
  src/main/java/com/likelion/backendplus4/talkpick/backend/auth/infrastructure/security/JwtProvider.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/security/SecurityConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/dto/NewsInfoDetailResponse.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/mapper/NewsInfoDetailResponseMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/in/NewsViewCountIncreaseUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsInfoDetailProviderService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsViewCountService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/domain/model/NewsInfoDetail.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/exception/error/NewsInfoErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/batch/config/ViewCountQuartzJobConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/batch/config/ViewCountQuartzTriggerConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/batch/executor/ViewCountSyncJobExecutor.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/adapter/NewsInfoDetailProviderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/application/port/out/NewsViewCountPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/entity/ArticleEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/mapper/ArticleEntityMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/redis/adapter/NewsViewCountRedisAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/NewsInfoDetailProviderController.java
  src/main/resources/application.yml
Labels: 기능 개발

#101 🐛 Fix: 최신 뉴스 페이징 오류 수정
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/in/NewsInfoProviderUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/out/NewsInfoProviderPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsInfoProviderService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/adapter/NewsInfoProviderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/jpa/repository/NewsInfoJpaRepository.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/NewsInfoProviderController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/dto/NewsInfoRequest.java
Labels: Overdue

#105 Feature/#104 뉴스id validation 추가
  build.gradle
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/domain/enums/NewsIdPrefix.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/NewsInfoDetailProviderController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/validator/NewsIdConstraint.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/validator/NewsIdValidator.java
  src/test/java/com/likelion/backendplus4/talkpick/backend/TalkpickBackendApplicationTests.java
  src/test/java/com/likelion/backendplus4/talkpick/backend/news/info/domain/enums/NewsIdPrefixTest.java
  src/test/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/validator/NewsIdConstraintTest.java
  src/test/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/validator/NewsIdValidatorTest.java
Labels: D-0

#115 ✨ Feat: 캐싱 허용 Url 추가
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: D-day

#112 ✨ Feature/#96 채팅방 캐싱 처리 및 저장 로직 구현
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/in/ChatUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/out/ChatMessageBrokerPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/out/ChatMessageCachePort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/out/ChatMessageDbPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/out/ChatMessageStreamPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/port/out/ChatSocketSenderPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/service/ChatService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/domain/model/ChatMessage.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/exception/error/ChatErrorCode.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/in/rabbitmq/RabbitMessageListener.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/jpa/ChatJpaAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/jpa/entity/ChatMessageEntity.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/jpa/repository/ChatMessageRepository.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/rabbitmq/RabbitChatMessageBrokerAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/redis/RedisChatMessageCacheAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/redis/RedisStreamAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/adapter/out/websocket/WebSocketSenderAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/infrastructure/support/mapper/ChatMessageMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/ChatController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/ChatRestController.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/dto/request/ChatMessageRequest.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/dto/response/ChatMessageResponse.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/support/mapper/ChatMessageRequestMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/support/mapper/ChatMessageResponseMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/support/mapper/SliceResponseChatMapper.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/rabbitmq/RabbitMQConfig.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/common/configuration/websocket/WebSocketConfig.java
Labels: D-day

#126 ✨ Feature/#125 메시지 타입 추가
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/application/service/ChatService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/domain/model/MessageType.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/chat/presentation/controller/support/mapper/ChatMessageRequestMapper.java
Labels: D-day

#129 Feature/#73 인기뉴스 조회서비스 구현 - Nginx IP 관련 문제 수정
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/in/NewsViewCountIncreaseUseCase.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/port/out/ClientInfoPort.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/application/service/NewsViewCountService.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/redis/adapter/NewsViewCountRedisAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/infrastructure/web/adapter/ClientInfoWebAdapter.java
  src/main/java/com/likelion/backendplus4/talkpick/backend/news/info/presentation/controller/NewsInfoDetailProviderController.java
  src/main/resources/application.yml
Labels: D-day
